case_study:
  name: Amatrice_catalog_test
  personal_folder: null
  download_data: true

geography:
  minlatitude: 42.25
  maxlatitude: 43.12
  minlongitude: 11.75
  maxlongitude: 14.00

dates:
  starttime: "2016-10-30"
  endtime: "2016-10-30"
  year: 2016

stations:
  network: "*"
  channel: "BH?,HH?,EH?"
  stations_list: "*"
  fdsn_clients:
    - IRIS

model:
  neural_network: PhaseNet
  model_type: original
  custom_model_path: null
  batch_size: 256
  p_threshold: 0.9
  s_threshold: 0.9
  wlength_seconds: 900

gamma:
  dims:
    - x(km)
    - y(km)
    - z(km)
  use_dbscan: true
  use_amplitude: true
  x_km:
    - 230
    - 620
  y_km:
    - 4650
    - 4800
  z_km:
    - 0
    - 60
  velocity:
    p: 7.0
    s: 4.0
  method: BGMM
  dbscan_eps: 25
  dbscan_min_samples: 3
  eikonal:
    z:
      - 0.0
      - 5.5
      - 16.0
      - 32.0
    p:
      - 5.5
      - 5.5
      - 6.7
      - 7.8
    vp_vs_ratio: 1.73
    h: 1.0
  filtering:
    min_picks_per_eq: 6
    min_p_picks_per_eq: 4
    min_s_picks_per_eq: 3
    max_sigma11: 1.5
    max_sigma22: 1.0
    max_sigma12: 1.0

analysis:
  log_filename: analisi_picking.log

plotting:
  gmt_library_path: ""
  gmt_grid_path: "@earth_relief_15s"
  region:
    - 12.5
    - 14.00
    - 42.00
    - 43.50
  map_title: Central Italy - Seismicity

hypoellipse:
  h71_min_p: 4
  h71_min_s: 2
  velocity_model_path: hypoellipse_inputs/grad.mod
  parameter_file_path: hypoellipse_inputs/improved.cfg

dd:
  max_gap: 180.0
  max_rms: 0.4
  max_erh: 0.8
  max_erz: 0.8

script11:
  max_dist_km_cc: 3.0
  cc_threshold: 0.7
  win_before: 0.2
  win_after: 0.8
  cc_max_lag: 0.5
  freq_min: 2.0
  freq_max: 15.0
  network: 3A

script12:
  thresholds_map:
    01-01: 0.1
    02-02: 0.2
    03-03: 0.3
    04-04: 0.4
    05-05: 0.5
    06-06: 0.6
    07-07: 0.7
    08-08: 0.8
    09-09: 0.9
