name: seismic-workflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - matplotlib
  - numpy
  - obspy
  - pandas
  - pygmt
  - pyproj
  - pyyaml
  - seaborn
  - pytorch
  - tqdm
  - pip:
      - seisbench
