import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
import re

BASE_DIR = None
THRESHOLDS_MAP = None
CSV_FILENAME = None
DPI = None
output_bar_path = None
output_line_path = None


def _apply_context(ctx):
    globals().update(ctx.legacy_globals())
    globals().update({
        "BASE_DIR": output_base,
        "THRESHOLDS_MAP": THRESHOLDS_MAP_12,
        "CSV_FILENAME": CSV_FILENAME_12,
        "DPI": THRESHOLD_ANALYSIS_DPI,
        "output_bar_path": output_bar_path_12,
        "output_line_path": output_line_path_12,
    })

def parse_folder_data(folder_suffix, thr_value):
    """
    Reads the wave statistics log and counts the events from the CSV file.
    """
    try:
        p_code, s_code = folder_suffix.split("-", 1)
        p_threshold = int(p_code) / 10
        s_threshold = int(s_code) / 10
    except (AttributeError, ValueError):
        print(f"Invalid threshold format: {folder_suffix}")
        return None

    p_label = str(p_threshold)
    s_label = str(s_threshold)
    folder_name = f"threshold_p{p_label}_s{s_label}"
    folder_path = os.path.join(
        BASE_DIR,
        folder_name,
        f"output_catalog_{p_label}",
        "gamma",
    )
    log_path = os.path.join(folder_path, 'picking_analysis.log')
    csv_path = os.path.join(folder_path, CSV_FILENAME)
    
    data = {'THR': thr_value}

    if os.path.exists(log_path):
        with open(log_path, 'r') as f:
            content = f.read()
            try:
                data['P_TOT'] = int(re.search(r"P-wave total:\s+(\d+)", content).group(1))
                data['S_TOT'] = int(re.search(r"S-wave total:\s+(\d+)", content).group(1))
                data['P_NO_GAMMA'] = int(re.search(r"Unassociated P-wave:\s+(\d+)", content).group(1))
                data['S_NO_GAMMA'] = int(re.search(r"Unassociated S-wave:\s+(\d+)", content).group(1))
                data['P_GAMMA'] = int(re.search(r"Associated P-wave:\s+(\d+)", content).group(1))
                data['S_GAMMA'] = int(re.search(r"Associated S-wave:\s+(\d+)", content).group(1))
            except (AttributeError, ValueError):
                print(f"Error parsing log in: {folder_name}")
                return None
    else:
        print(f"Log not found in: {folder_name}")
        return None

    if os.path.exists(csv_path):
        try:
            temp_df = pd.read_csv(csv_path)
            data['N_EVE'] = len(temp_df)
        except Exception as e:
            print(f"Error reading CSV in {folder_name}: {e}")
            data['N_EVE'] = 0
    else:
        print(f"CSV not found in: {folder_name}")
        data['N_EVE'] = 0
            
    return data

def run(ctx):
    _apply_context(ctx)

    print("Starting folder processing...")
    results = []
    for folder_suffix, thr_value in THRESHOLDS_MAP.items():
        row = parse_folder_data(folder_suffix, thr_value)
        if row:
            results.append(row)

    df = pd.DataFrame(results)

    if df.empty:
        print("\nNo data found!")
        print("    This script compares the results of multiple runs with different thresholds.")
        print("    For each threshold (e.g., 01-01, 02-02, ...) there must be a folder:")
        print(f"      {BASE_DIR}/threshold_pX_sY/output_catalog_X/gamma/")
        print("    containing the 'picking_analysis.log' file (generated by the gamma-analysis command).")
        print("\n    If you have executed the pipeline only once, this script has no data to compare.")
        return

    df = df.sort_values('THR')

    print(f"Saving histograms: {output_bar_path}")
    x = np.arange(len(df['THR']))
    bar_width = 0.25
    colors = ['royalblue', 'red', 'orange']

    fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

    # P-phase
    ax1.bar(x - bar_width, df['P_TOT'], width=bar_width, label='P TOT', color=colors[0])
    ax1.bar(x, df['P_NO_GAMMA'], width=bar_width, label='P NO ASSOCIATION', color=colors[1])
    ax1.bar(x + bar_width, df['P_GAMMA'], width=bar_width, label='P ASSOCIATION', color=colors[2])
    ax1.set_title('P-phase vs THR', fontsize=14, fontweight='bold')
    ax1.set_xticks(x)
    ax1.set_xticklabels(df['THR'])
    ax1.legend(loc='upper center', bbox_to_anchor=(0.5, 1.15), ncol=3, frameon=False)
    ax1.grid(axis='y', linestyle='--', alpha=0.7)

    # S-phase
    ax2.bar(x - bar_width, df['S_TOT'], width=bar_width, label='S TOT', color=colors[0])
    ax2.bar(x, df['S_NO_GAMMA'], width=bar_width, label='S NO ASSOCIATION', color=colors[1])
    ax2.bar(x + bar_width, df['S_GAMMA'], width=bar_width, label='S ASSOCIATION', color=colors[2])
    ax2.set_title('S-phase vs THR', fontsize=14, fontweight='bold')
    ax2.set_xticks(x)
    ax2.set_xticklabels(df['THR'])
    ax2.legend(loc='upper center', bbox_to_anchor=(0.5, 1.15), ncol=3, frameon=False)
    ax2.grid(axis='y', linestyle='--', alpha=0.7)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(output_bar_path, format='pdf', dpi=DPI)
    plt.close()

    print(f"Saving line plots: {output_line_path}")
    fig2, axes2 = plt.subplots(3, 2, figsize=(16, 18))
    axes2 = axes2.flatten()

    # Associations
    axes2[0].plot(df['THR'], df['P_NO_GAMMA'], marker='o', label='P_NO_GAMMA')
    axes2[0].plot(df['THR'], df['P_GAMMA'], marker='s', label='P_GAMMA')
    axes2[0].set_title('P_NO_GAMMA and P_GAMMA vs THR')

    axes2[1].plot(df['THR'], df['S_NO_GAMMA'], marker='o', label='S_NO_GAMMA')
    axes2[1].plot(df['THR'], df['S_GAMMA'], marker='s', label='S_GAMMA')
    axes2[1].set_title('S_NO_GAMMA and S_GAMMA vs THR')

    # Single charts
    cols_single = ['P_TOT', 'S_TOT', 'N_EVE']
    for i, col in enumerate(cols_single):
        ax = axes2[i + 2]
        ax.plot(df['THR'], df[col], marker='o', color='tab:blue', label=col)
        ax.set_title(f'Line Chart of {col} vs THR')

    for ax in axes2[:5]:
        ax.set_xlabel('THR')
        ax.set_ylabel('Value')
        ax.grid(True)
        ax.legend()
        ax.ticklabel_format(style='sci', axis='y', scilimits=(0,3))

    axes2[-1].axis('off')
    plt.tight_layout()
    plt.savefig(output_line_path, format='pdf', dpi=DPI)
    plt.close()


def main():
    from seimlai.context import build_context

    run(build_context("user_configuration/config.yaml"))


run_threshold_analysis = run


if __name__ == "__main__":
    main()
